# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking
# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands

after-login-command = []
# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []
# Start AeroSpace at login
start-at-login = true
# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30
# Possible values: tiles|accordion
default-root-container-layout = 'scroll'
# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
# tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'
# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]
niri-focused-width-ratio = 0.67

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = "${HOME}/bin:${HOME}/.nix-profile/bin:/etc/profiles/per-user/${USER}/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:${PATH}"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
# In this example, 24 is a default value when there is no match.
# Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main]

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
# do script
# activate
# end tell'
# '''
ctrl-shift-alt-a = "exec-and-forget ghostty"
ctrl-shift-alt-e = "exec-and-forget emacsclient -c -n -a ''"
# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-minus = 'layout tiles horizontal vertical'
ctrl-alt-equal = 'layout accordion horizontal vertical'
ctrl-alt-s = 'layout scroll'
alt-shift-f = "fullscreen"
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'
# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'
# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-6 = 'workspace 6'
ctrl-alt-7 = 'workspace 7'
ctrl-alt-8 = 'workspace 8'
ctrl-alt-9 = 'workspace 9'
ctrl-alt-0 = "workspace 10"
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=service']
alt-shift-quote = ['mode resize', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=resize']

# Declare 'resize' binding mode
[mode.resize.binding]
left = 'resize width -50'
up = 'resize height +50'
down = 'resize height -50'
right = 'resize width +50'
e = "balance-sizes"
esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

[mode.service.binding]
esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
# reset layout
r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
# Toggle between floating and tiling layout
f = [
  'layout floating tiling',
  'mode main',
  'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main'
]
backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
left = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
down = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
up = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
right = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

[[on-window-detected]]
run = 'move-node-to-workspace 8'
if.app-id = 'com.apple.mail'

# Book/Picture Preview
[[on-window-detected]]
run = 'move-node-to-workspace 8'
if.app-id = 'com.apple.iCal'

[[on-window-detected]]
run = 'move-node-to-workspace 8'
if.app-id = 'com.microsoft.Outlook'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.apple.finder'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.apple.iBooksX'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.apple.Preview'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.duxiaoman.manruliu'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.electron.lark'

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 9']
if.app-id = 'com.tencent.xinWeChat'

[[on-window-detected]]
run = ['layout floating']
if.app-id = '-.RVLSession'

[[on-window-detected]]
run = ['layout floating']
if.app-id = 'com.bitwarden.desktop'

[[on-window-detected]]
run = ['layout floating']
if.app-id = 'com.apple.ActivityMonitor'

[[on-window-detected]]
run = ['layout floating']
if.app-id = 'com.apple.Music'

[workspace-to-monitor-force-assignment]
"1" = "1"
"2" = "1"
"3" = "1"
"4" = "1"
"5" = "1"
"6" = "1"
"7" = "1"
"8" = "built-in"
"9" = "built-in"
"10" = "built-in"
